# This is a basic workflow to help you get started with Actions

name: Publish
on:
  workflow_dispatch:
  release:
    types:
    - created
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install package
      run: npm install
    - name: Publish to NPM
      if: startsWith( github.ref, 'refs/tags/v')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Publish to Open VSX Registry
      if: startsWith( github.ref, 'refs/tags/v')
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.OPENVSX_PAT }}
    - name: Publish to Visual Studio Marketplace
      if: startsWith( github.ref, 'refs/tags/v')
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.VSMARKETPLACE_PAT }}
        registryUrl: https://marketplace.visualstudio.com
